version: '3.9'

services:
  # Serviço para o seu aplicativo React
  my-crypto-app:
    image: node:latest
    container_name: my-crypto-app
    working_dir: /app
    volumes:
      - ./my-crypto-app:/app
    ports:
      - "3002:3001" # Mapeamento da porta do contêiner React para 3002
    command: sh -c "npm install && npm start" # Comando para instalar dependências e iniciar o app

  # Serviço para o backend Flask
  sentiment-analysis:
    build: ./sentiment-analysis
    container_name: sentiment-analysis
    volumes:
      - ./sentiment-analysis:/app
    ports:
      - "5000:5000" # Mapeamento da porta do contêiner Flask para 5000
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/sentiment_db
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}

  # Serviço para o Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Mapeamento da porta padrão do Redis

  # Serviço para o MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Mapeamento da porta padrão do MongoDB

  # Serviço para o LocalStack da AWS
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # Mapeamento da porta do LocalStack
    environment:
      - SERVICES=s3,sqs,lambda,dynamodb,apigateway,cloudwatch
      - DEFAULT_REGION=us-east-1








